# Generated by Django 3.2.6 on 2021-08-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHTPV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRG_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='RHTPV.members')),
                ('member_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_status', to='RHTPV.memberstatus')),
                ('member_status_spe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_status_spe', to='RHTPV.memberstatusspe')),
            ],
        ),
    ]
