# Generated by Django 3.2.6 on 2021-08-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHTPV', '0002_srg_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SR_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_member', to='RHTPV.members')),
                ('member_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_member_status', to='RHTPV.memberstatus')),
                ('member_status_spe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_member_status_spe', to='RHTPV.memberstatusspe')),
                ('srg_Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_srg_Service', to='RHTPV.srg_service')),
            ],
        ),
        migrations.CreateModel(
            name='SRTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('sr_Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sr_Service', to='RHTPV.sr_service')),
            ],
        ),
    ]
